### ISSUE TITLE
Getting The requested URL returned error: 400 

### ISSUE THREAD

**Issue by sandipmgiri** [gene1wood/fork-github-repo#4]
Getting following error while forking "expressions" project in GitHub  :

```
$  fork-github-repo https://github.com/timoxley/expressions.git

Forked https://github.com/timoxley/expressions.git to https://github.com/sandipmgiri/expressions.git
Directory /root/tmp/expressions exists already, assuming it's a clone
Remote "upstream" already exists in /root/tmp/expressions
Traceback (most recent call last):
  File "/usr/local/bin/fork-github-repo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/fork_github_repo/__init__.py", line 165, in main
    config['branch']
  File "/usr/local/lib/python2.7/dist-packages/fork_github_repo/__init__.py", line 146, in fork_and_clone_repo
    )(upstream_remote.fetch)()
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 757, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 643, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 292, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v upstream
  stderr: 'fatal: unable to access 'https://github.com/timoxley/expressions.git expressions/': The requested URL returned error: 400'

```

Any comments would appreciate.Thanks!

**Comment by gene1wood** [comment]
I got the same thing on another repo. I'll have to look into this

**Comment by mathben** [comment]
It's now fixed, we can close this issue.

**Comment by gene1wood** [comment]
@mathben Do you suspect this is an intermittent issue and GitHub is intermittently returning a 400 (in which case this tool could just handle that case more gracefully), or was this a consistent problem in the past but now no longer occurs?

**Comment by mathben** [comment]
I assume it was a consistent problem in the past but now no longer occurs, but I have no proof.
I only know that I ran the test and now it works.
